---
output: pdf_document
---

Este documento está destinado a un mejor conocimiento de aspectos claves de la Teoría de Juegos, y la aplicación de estos conocimientos para explicar dos tipos de juegos: uno desde un punto de vista únicamente teórico; y el otro también aproximándonos a un carácter más práctico.

En el primer capítulo comentaremos los distintos elementos que presenta un juego como son los jugadores, las reglas, etc. Citaremos el principio de racionalidad, en el que nos basamos para suponer ciertas estrategias que siguen los jugadores. Posteriormente analizaremos el concepto de utilidad de un jugador en un juego, usándolo para determinar su actitud ante el riesgo (arriesgado, neutro y conservador).

A continuación, en el segundo capítulo empezamos clasificando los juegos según distintos criterios:  el numero de jugadores; cómo se reparten las ganancias entre los jugadores; si se permite la cooperación entre los jugadores, etc. Al terminar pasamos a comentar las dos formas comunes de representación que tiene un juego, la forma normal y la forma extensiva, donde expondremos un par de ejemplos sencillos para que en los dos juegos que analizamos más adelante no nos resulte extraño esta forma de representarlos. Para acabar el capítulo, se detallará el concepto de equilibrio de Nash y lo usamos para intentar hallar el equilibrio de los ejemplos que se utilizan en el apartado anterior.

A partir de este momento entramos en un nuevo bloque del documento. Nos centraremos en intentar utilizar los conocimientos anteriormente explicados, junto con elementos de simulación como los métodos de Montecarlo, para entender y explicar ambos juegos.

En el capítulo 3 y 4 nos centramos en el juego del Blackjack. Inicialmente comentando cuales son las reglas establecidas con las que trabajamos (suele haber ciertas diferencias en el juego respecto a jugar en Europa o América), e intentamos clasificar el Blackjack según los criterios que se comentan en el capitulo 2. Posteriormente intentamos hallar la mejor manera de jugar a este juego, es decir, buscar la estrategia óptima.

Buscamos unos "topes" que diremos vulgarmente, en función de si la mano que posee el jugador es dura o blanda, para ver a partir de la suma de las cartas que tiene el jugador, y de la carta visible del crupier, si es mejor pararse o pedir una carta más. Todo ello lo haremos examinando la esperanza del jugador si se planta, o si pide una carta más, y en función de cuál sea más alta, nos decantaremos por una u otra opción.

En el capitulo 4 nos centramos en el estudio individual de cada situación, comenzando por calcular las probabilidades de la suma final de las cartas del crupier, en función de la carta visible del mismo. Usaremos esta matriz de probabilidades, para hallar cuales son las estrategias óptimas en el caso de una mano dura, o blanda. Realizamos lo mismo para el caso de si es mejor doblarse o no, si es mejor abrirse y jugar a dos manos en los casos en los que se pueda, y si es buena opción asegurarnos ante un posible Blackjack del crupier. Finalizaremos calculando el valor esperado del juego si jugásemos la estrategia óptima que hemos obtenido anteriormente. 

Para terminar, en el ultimo capítulo trataremos el VNM-Poker y el Khun-Poker, explicando cuales son sus diferencias y usando la forma extensiva para representar el juego y explicar las estrategias posibles que de cada jugador, cuales están dominadas por otras, y cuales serían las mejores en las distintas situaciones del juego.

En el apartado del apéndice se encuentran otras dos secciones. En la primera se muestra la ganancia esperada en cada situación del juego que pudiera presentársele al jugador si jugase con la estrategia óptima, que se detalla en el capítulo 4 para cada uno de los casos que ahí se analizan. En la segunda, se encuentra el código que se ha utilizado para el cálculo de la matriz de probabilidades del crupier, las estrategias y ganancias óptimas y el valor esperado del juego.